In [202]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Working with dataset

In [203]:
# Importing the dataset
dataset = pd.read_csv('churn_train.txt')


In [204]:
X = dataset.iloc[:, [0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].values
y = dataset.iloc[:, 19].values

In [205]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3333 entries, KS to TN
Data columns (total 20 columns):
st              3333 non-null int64
 acclen         3333 non-null int64
 arcode         3333 non-null object
 phnum          3333 non-null object
 intplan        3333 non-null object
 voice          3333 non-null int64
nummailmes      3333 non-null float64
 tdmin          3333 non-null int64
 tdcal          3333 non-null float64
 tdchar         3333 non-null float64
 temin          3333 non-null int64
 tecal          3333 non-null float64
 tecahr         3333 non-null float64
 tnmin          3333 non-null int64
 tn cal         3333 non-null float64
 tnchar         3333 non-null float64
 timin          3333 non-null int64
 tical          3333 non-null float64
 tichar ncsc    3333 non-null int64
 label          3333 non-null object
dtypes: float64(8), int64(8), object(4)
memory usage: 546.8+ KB


In [206]:
dataset

st   acclen     arcode  phnum  intplan   voice  nummailmes   tdmin  \
KS  128      415   382-4657     no      yes      25       265.1     110   
OH  107      415   371-7191     no      yes      26       161.6     123   
NJ  137      415   358-1921     no       no       0       243.4     114   
OH   84      408   375-9999    yes       no       0       299.4      71   
OK   75      415   330-6626    yes       no       0       166.7     113   
AL  118      510   391-8027    yes       no       0       223.4      98   
MA  121      510   355-9993     no      yes      24       218.2      88   
MO  147      415   329-9001    yes       no       0       157.0      79   
LA  117      408   335-4719     no       no       0       184.5      97   
WV  141      415   330-8173    yes      yes      37       258.6      84   
IN   65      415   329-6603     no       no       0       129.1     137   
RI   74      415   344-9403     no       no       0       187.7     127   
IA  168      408   363-1107     no       no       0       128.8      96   
MT   95      510   394-8006     no       no       0       156.6      88   
IA   62      415   366-9238     no       no       0       120.7      70   
NY  161      415   351-7269     no       no       0       332.9      67   
ID   85      408   350-8884     no      yes      27       196.4     139   
VT   93      510   386-2923     no       no       0       190.7     114   
VA   76      510   356-2992     no      yes      33       189.7      66   
TX   73      415   373-2782     no       no       0       224.4      90   
FL  147      415   396-5800     no       no       0       155.1     117   
CO   77      408   393-7984     no       no       0        62.4      89   
AZ  130      415   358-1958     no       no       0       183.0     112   
SC  111      415   350-2565     no       no       0       110.4     103   
VA  132      510   343-4696     no       no       0        81.1      86   
NE  174      415   331-3698     no       no       0       124.3      76   
WY   57      408   357-3817     no      yes      39       213.0     115   
MT   54      408   418-6412     no       no       0       134.3      73   
MO   20      415   353-2630     no       no       0       190.0     109   
HI   49      510   410-7789     no       no       0       119.3     117   
..  ...      ...        ...    ...      ...     ...         ...     ...   
WI  114      415   373-7308     no      yes      26       137.1      88   
IL   71      510   330-7137    yes       no       0       186.1     114   
IN   58      415   406-8445     no      yes      22       224.1     127   
AL  106      408   404-5283     no      yes      29        83.6     131   
OK  172      408   398-3632     no       no       0       203.9     109   
IA   45      415   399-5763     no       no       0       211.3      87   
VT  100      408   340-9449    yes       no       0       219.4     112   
NY   94      415   363-1123     no       no       0       190.4      91   
LA  128      415   361-2170     no       no       0       147.7      94   
SC  181      408   406-6304     no       no       0       229.9     130   
ID  127      408   392-5090     no       no       0       102.8     128   
MO   89      415   373-7713     no       no       0       178.7      81   
ME  149      415   392-1376     no      yes      18       148.5     106   
MS  103      510   390-6388     no      yes      29       164.1     111   
SD  163      415   379-7290    yes       no       0       197.2      90   
OK   52      415   397-9928     no       no       0       124.9     131   
WY   89      415   378-6924     no       no       0       115.4      99   
GA  122      510   411-5677    yes       no       0       140.0     101   
VT   60      415   400-2738     no       no       0       193.9     118   
MD   62      408   409-1856     no       no       0       321.1     105   
IN  117      415   362-5899     no       no       0       118.4     126   
WV  159      415   377-1164   

In [207]:
X

array([[128, 415, ' no', ..., 3, 2.7, 1],
       [107, 415, ' no', ..., 3, 3.7, 1],
       [137, 415, ' no', ..., 5, 3.29, 0],
       ...,
       [28, 510, ' no', ..., 6, 3.81, 2],
       [184, 510, ' yes', ..., 10, 1.35, 2],
       [74, 415, ' no', ..., 4, 3.7, 0]], dtype=object)

In [208]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
labelencoder_X_3 = LabelEncoder()
X[:, 3] = labelencoder_X_3.fit_transform(X[:, 3])
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
#label encoder is enough as we have binary variable.

In [209]:
X.shape

(3333, 18)

In [210]:
X

array([[128, 415, 0, ..., 3, 2.7, 1],
       [107, 415, 0, ..., 3, 3.7, 1],
       [137, 415, 0, ..., 5, 3.29, 0],
       ...,
       [28, 510, 0, ..., 6, 3.81, 2],
       [184, 510, 1, ..., 10, 1.35, 2],
       [74, 415, 0, ..., 4, 3.7, 0]], dtype=object)

In [211]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [212]:

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\chall\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [213]:
# Part 2 -  making the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
import sys

# Initialising the ANN
classifier = Sequential()

In [214]:
classifier.add(Dense(output_dim = 10, init = 'glorot_uniform', activation = 'relu', input_dim = 18))#1st hidden layer
classifier.add(Dropout(0.4, noise_shape=None, seed=None))#dropout regularisation
classifier.add(Dense(output_dim = 12, init = 'glorot_uniform', activation = 'relu'))
classifier.add(Dropout(0.2, noise_shape=None, seed=None))
classifier.add(Dense(output_dim = 14, init = 'glorot_uniform', activation = 'relu'))
classifier.add(Dropout(0.1, noise_shape=None, seed=None))
classifier.add(Dense(output_dim = 1, init = 'glorot_uniform', activation = 'sigmoid'))


C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=18, units=10, kernel_initializer="glorot_uniform")`
  """Entry point for launching an IPython kernel.
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12, kernel_initializer="glorot_uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=14, kernel_initializer="glorot_uniform")`
  """
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="glorot_uniform")`
  import sys


Dropout is used to avoid overfitting.As we go on with the hidden layers, The information becomes more and more important so I have reduced dropout fraction accordinlgy to fit under fitting .

In [215]:
# Compiling the ANN
classifier.compile(optimizer = 'rmsprop', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [216]:

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 25, nb_epoch = 100)


C:\Users\chall\Anaconda3\lib\site-packages\keras\models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
2666/2666 [==============================] - 1s 191us/step - loss: 0.5299 - acc: 0.8136
Epoch 2/100
2666/2666 [==============================] - 0s 56us/step - loss: 0.4574 - acc: 0.8503
Epoch 3/100
2666/2666 [==============================] - 0s 53us/step - loss: 0.4381 - acc: 0.8530
Epoch 4/100
2666/2666 [==============================] - 0s 54us/step - loss: 0.4134 - acc: 0.8518
Epoch 5/100
2666/2666 [==============================] - 0s 53us/step - loss: 0.3915 - acc: 0.8530
Epoch 6/100
2666/2666 [==============================] - 0s 51us/step - loss: 0.3874 - acc: 0.8563
Epoch 7/100
2666/2666 [==============================] - 0s 53us/step - loss: 0.3805 - acc: 0.8552
Epoch 8/100
2666/2666 [==============================] - 0s 53us/step - loss: 0.3725 - acc: 0.8578
Epoch 9/100
2666/2666 [==============================] - 0s 52us/step - loss: 0.3713 - acc: 0.8582
Epoch 10/100
2666/2666 [==============================] - 0s 53us/step - loss: 0.3559 - acc: 0.8601
Epoch 11

2666/2666 [==============================] - 0s 51us/step - loss: 0.2913 - acc: 0.8965
Epoch 84/100
2666/2666 [==============================] - 0s 50us/step - loss: 0.2755 - acc: 0.9014
Epoch 85/100
2666/2666 [==============================] - 0s 53us/step - loss: 0.2901 - acc: 0.8950
Epoch 86/100
2666/2666 [==============================] - 0s 58us/step - loss: 0.2862 - acc: 0.8976
Epoch 87/100
2666/2666 [==============================] - 0s 59us/step - loss: 0.2759 - acc: 0.9032
Epoch 88/100
2666/2666 [==============================] - 0s 52us/step - loss: 0.2853 - acc: 0.8983
Epoch 89/100
2666/2666 [==============================] - 0s 51us/step - loss: 0.2777 - acc: 0.9006
Epoch 90/100
2666/2666 [==============================] - 0s 51us/step - loss: 0.2890 - acc: 0.8983
Epoch 91/100
2666/2666 [==============================] - 0s 52us/step - loss: 0.2760 - acc: 0.9032
Epoch 92/100
2666/2666 [==============================] - 0s 50us/step - loss: 0.2849 - acc: 0.8983
Epoch 93/100


In [217]:

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [218]:
cm

array([[579,   0],
       [ 67,  21]])

## Fitting with the complete dataset and predicting the test set

In [219]:
data_test = pd.read_csv('churn_test.txt')

In [220]:
X_test_out = data_test.iloc[:, [0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]].values
y_test_out = data_test.iloc[:,-1].values

In [221]:
X_test_out.shape

(1667, 18)

In [222]:
X_test_out

array([[101, 510, ' no', ..., 3, 2.86, 3],
       [137, 510, ' no', ..., 7, 2.57, 0],
       [103, 408, ' no', ..., 6, 3.7, 1],
       ...,
       [61, 415, ' no', ..., 4, 3.67, 1],
       [109, 510, ' no', ..., 6, 2.3, 0],
       [86, 415, ' no', ..., 16, 2.51, 0]], dtype=object)

In [223]:
y_test_out

array([' False.', ' False.', ' False.', ..., ' False.', ' False.',
       ' False.'], dtype=object)

In [224]:
X_test_out[:,3] = labelencoder_X_3.transform(X_test_out[:,3])
X_test_out[:,2] = labelencoder_X_2.transform(X_test_out[:,2])
y_test_out = labelencoder_y.transform(y_test_out)

In [225]:
classifier_totalt = classifier

In [226]:

# Fitting the ANN to the Training set
classifier_totalt.fit(X, y, batch_size = 25, nb_epoch = 100)


Epoch 1/100
3333/3333 [==============================] - 0s 58us/step - loss: 5.6187 - acc: 0.6427
Epoch 2/100
  25/3333 [..............................] - ETA: 0s - loss: 7.6875 - acc: 0.5200

C:\Users\chall\Anaconda3\lib\site-packages\keras\models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


3333/3333 [==============================] - 0s 58us/step - loss: 3.6075 - acc: 0.7714
Epoch 3/100
3333/3333 [==============================] - 0s 55us/step - loss: 2.9747 - acc: 0.8098
Epoch 4/100
3333/3333 [==============================] - 0s 57us/step - loss: 2.7956 - acc: 0.8227
Epoch 5/100
3333/3333 [==============================] - 0s 58us/step - loss: 2.6715 - acc: 0.8296
Epoch 6/100
3333/3333 [==============================] - 0s 57us/step - loss: 2.6996 - acc: 0.8284
Epoch 7/100
3333/3333 [==============================] - 0s 54us/step - loss: 2.6971 - acc: 0.8293
Epoch 8/100
3333/3333 [==============================] - 0s 57us/step - loss: 2.5753 - acc: 0.8359
Epoch 9/100
3333/3333 [==============================] - 0s 65us/step - loss: 2.5639 - acc: 0.8374
Epoch 10/100
3333/3333 [==============================] - 0s 55us/step - loss: 2.4186 - acc: 0.8437
Epoch 11/100
3333/3333 [==============================] - 0s 53us/step - loss: 2.2559 - acc: 0.8530
Epoch 12/100
3333/33

3333/3333 [==============================] - 0s 52us/step - loss: 2.2251 - acc: 0.8551
Epoch 85/100
3333/3333 [==============================] - 0s 50us/step - loss: 2.2175 - acc: 0.8548
Epoch 86/100
3333/3333 [==============================] - 0s 51us/step - loss: 2.2509 - acc: 0.8551
Epoch 87/100
3333/3333 [==============================] - 0s 50us/step - loss: 2.1926 - acc: 0.8551
Epoch 88/100
3333/3333 [==============================] - 0s 47us/step - loss: 2.2051 - acc: 0.8551
Epoch 89/100
3333/3333 [==============================] - 0s 56us/step - loss: 2.2181 - acc: 0.8551
Epoch 90/100
3333/3333 [==============================] - 0s 49us/step - loss: 2.2094 - acc: 0.8554
Epoch 91/100
3333/3333 [==============================] - 0s 55us/step - loss: 2.2135 - acc: 0.8551
Epoch 92/100
3333/3333 [==============================] - 0s 50us/step - loss: 2.2162 - acc: 0.8551
Epoch 93/100
3333/3333 [==============================] - 0s 54us/step - loss: 2.2107 - acc: 0.8551
Epoch 94/100


In [227]:

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred_classifier = classifier.predict(X_test_out)
y_pred_classifier = (y_pred_classifier > 0.5)
y_pred_totalt = classifier_totalt.predict(X_test_out)
y_pred_totalt = (y_pred_totalt > 0.5)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_out_classifier = confusion_matrix(y_test_out, y_pred_classifier)
cm_out_classifier_total = confusion_matrix(y_test_out, y_pred_totalt)

In [228]:
cm_out_classifier

array([[1443,    0],
       [ 224,    0]])

In [229]:
cm_out_classifier_total

array([[1443,    0],
       [ 224,    0]])